import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "../context/socketContext";
import UserAuthProvider  from '../context/userContext';
import { StrictMode } from "react";
import { headers } from "next/headers";
export const dynamic = 'force-dynamic';

import Navbar from "../components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const headerList = await headers();
  const userName = headerList.get('x-user-name')
  const userEmail = headerList.get('x-user-email');

  console.log(userName + userEmail);
  return (
    <StrictMode>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SocketProvider>
          <UserAuthProvider userName={userName} userEmail={userEmail}>
          <Navbar/>
        {children}
        </UserAuthProvider>
        </SocketProvider>
      </body>
    </html>
    </StrictMode>
  );
}
